# -*- coding: utf-8 -*-
"""633-Quick Quiz: Drag-and-Drop Software Categorization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GZvNN29CeFk5nfvIR6KRn0RhUxAHNTnA
"""

# ==============================================================================
# CS633 Fall 2026 - Production Grade Final Term Project Infrastructure (Strict)
# Role: Senior Developer (Jiankai)
# Tech Stack: Python 3.10 / Flask / MongoDB Atlas (Cloud Persistent Instance)
# PART 1: Core Initialization, Security Compliance, and Student View Engine
# ==============================================================================

code_part1 = """from flask import Flask, request, jsonify, render_template_string, redirect, url_for
from pymongo import MongoClient
import os

app = Flask(__name__)

# ------------------------------------------------------------------------------
# 1. DATABASE PERSISTENCE LAYER (Zero-Leak Environment Variable Injection)
# ------------------------------------------------------------------------------
# SECURITY ENFORCEMENT: Transferred secrets entirely to environment variables.
# Source code contains ZERO hardcoded passwords to pass strict security compliance audits.
MONGO_URI = os.environ.get("MONGO_URI")
ADMIN_PASSWORD = os.environ.get("ADMIN_PASSWORD")

try:
    if not MONGO_URI or not ADMIN_PASSWORD:
        raise ValueError("Critical Security Violation: Required environment variables are missing.")

    # Constraint: 3-second explicit connection timeout to prevent Render thread hang
    client = MongoClient(MONGO_URI, serverSelectionTimeoutMS=3000)
    db = client['quiz_db']
    quizzes_col = db['quizzes']
    results_col = db['results']
    client.server_info()  # Force synchronous ping to validate cloud network connectivity
    db_mocked = False
    print("✓ Production Cloud MongoDB Atlas Connected.")
except Exception as e:
    # Fault-Tolerance Rollback: Triggers full memory mock layer to preserve offline functionality
    print(f"⚠️ Warning: Cloud DB unreachable or environment variables unset. Activating deep mock: {e}")
    class DeepMockCollection:
        def __init__(self):
            self.cache = {
                "quiz_id": "global_quiz",
                "title": "Application Functional Categorization Quiz",
                "items": [
                    {"id": "item_1", "content_text": "Steam", "correct_tag": "tag_game", "display_asset": "🎮 Steam"},
                    {"id": "item_2", "content_text": "Zoom", "correct_tag": "tag_chat", "display_asset": "📹 Zoom"}
                ]
            }
        def count_documents(self, fltr): return 1 if self.cache else 0
        def insert_one(self, doc): self.cache = doc
        def find_one(self, fltr): return self.cache
        def update_one(self, fltr, update, upsert=True):
            self.cache = update['$set']
    quizzes_col = DeepMockCollection()
    results_col = DeepMockCollection()
    db_mocked = True

# Database Seeding: Inject baseline records matching M2 schema goals (Steam/Zoom definitions)
if quizzes_col.count_documents({"quiz_id": "global_quiz"}) == 0:
    quizzes_col.insert_one({
        "quiz_id": "global_quiz",
        "title": "Application Functional Categorization Quiz",
        "items": [
            {"id": "item_1", "content_text": "Steam", "correct_tag": "tag_game", "display_asset": "🎮 Steam"},
            {"id": "item_2", "content_text": "Zoom", "correct_tag": "tag_chat", "display_asset": "📹 Zoom"}
        ]
    })

# ------------------------------------------------------------------------------
# 2. STUDENT USER ENGINE - DYNAMIC TEMPLATE RENDERING (M1-09 Frontend UI)
# ------------------------------------------------------------------------------
STUDENT_TEMPLATE = \"\"\"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CS633 - Student Portal</title>
    <style>
        body { font-family: 'Segoe UI', sans-serif; text-align: center; background: #eedec5; color: #333; padding: 40px; }
        .app-card { max-width: 800px; margin: auto; background: #ffffff; padding: 45px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.06); }
        .flex-row { display: flex; justify-content: center; gap: 25px; margin: 35px 0; min-height: 90px; flex-wrap: wrap; }
        .quiz-item { font-size: 20px; font-weight: bold; cursor: grab; padding: 14px 28px; border: 2px solid #ccc; background: #fff; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.05); }
        .drop-target { width: 240px; height: 190px; border: 3px dashed #666; background: #fafafa; display: flex; align-items: center; justify-content: center; font-weight: bold; border-radius: 12px; }
        button { background-color: #2b7a78; color: white; padding: 14px 40px; font-size: 16px; border: none; border-radius: 5px; cursor: pointer; font-weight: bold; }
        .admin-nav { display: block; margin-top: 35px; color: #e07a5f; text-decoration: none; font-weight: bold; font-size: 15px; }
    </style>
</head>
<body>
    <div class="app-card">
        <h2>{{ quiz.title }}</h2>
        <p style="color: #666;">Drag terms below into their verified architectural category targets:</p>

        <!-- ZERO HARDCODING: Draggable terms populated entirely via MongoDB item stream -->
        <div class="flex-row">
            {% for item in quiz.items %}
                <div id="{{ item.id }}" class="quiz-item" draggable="true" ondragstart="startDrag(event)">{{ item.display_asset }}</div>
            {% endfor %}
        </div>

        <div class="flex-row">
            <div id="tag_game" class="drop-target" ondrop="executeDrop(event)" ondragover="allowDrop(event)">Game Domain Target</div>
            <div id="tag_chat" class="drop-target" ondrop="executeDrop(event)" ondragover="allowDrop(event)">Communication Target</div>
        </div>

        <br>
        <button onclick="commitStudentResults()">Verify and Submit to Cloud DB</button>
        <a class="admin-nav" href="/edit-quiz">⚙️ Access Instructor Dashboard (Authentication Required)</a>
    </div>

    <script>
        function allowDrop(ev) { ev.preventDefault(); }
        function startDrag(ev) { ev.dataTransfer.setData("text", ev.target.id); }
        function executeDrop(ev) {
            ev.preventDefault();
            var elementId = ev.dataTransfer.getData("text");
            ev.target.appendChild(document.getElementById(elementId));
        }
        function commitStudentResults() {
            let payload = {};
            {% for item in quiz.items %}
                if (document.getElementById("tag_game").contains(document.getElementById("{{ item.id }}"))) {
                    payload["{{ item.id }}"] = "tag_game";
                } else if (document.getElementById("tag_chat").contains(document.getElementById("{{ item.id }}"))) {
                    payload["{{ item.id }}"] = "tag_chat";
                } else {
                    payload["{{ item.id }}"] = "unassigned";
                }
            {% endfor %}

            fetch('/api/submit', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify(payload)
            })
            .then(res => res.json())
            .then(out => {
                alert("🎯 Evaluation Complete! Score: " + out.score + "/100 generated and written to active MongoDB namespace.");
            });
        }
    </script>
</body>
</html>
\"\"\"
"""

with open("app.py", "w", encoding="utf-8") as f:
    f.write(code_part1)

print("✓ Part 1 (Strict Vacuum Security) successfully initialized and written into app.py!")

# ==============================================================================
# CS633 Fall 2026 - Production Grade Final Term Project Infrastructure (Strict)
# Role: Senior Developer (Jiankai)
# PART 2: Instructor Console, Dynamic Input Expansion, and Grading Controller
# ==============================================================================

code_part2 = """
# ------------------------------------------------------------------------------
# 3. INSTRUCTOR WORKSPACE ENGINE - DYNAMIC INPUT MULTIPLICITY (M1 Management Goal)
# ------------------------------------------------------------------------------
INSTRUCTOR_TEMPLATE = \"\"\"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CS633 - Instructor Workspace</title>
    <style>
        body { font-family: 'Segoe UI', sans-serif; background: #eedec5; color: #333; padding: 40px; }
        .admin-card { max-width: 650px; margin: auto; background: #ffffff; padding: 40px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.08); }
        .item-row { display: flex; gap: 15px; margin-bottom: 15px; background: #f9f9f9; padding: 15px; border-radius: 6px; border-left: 4px solid #e07a5f; }
        label { font-weight: bold; display: block; margin-bottom: 5px; }
        input, select { padding: 10px; border: 1px solid #ccc; border-radius: 4px; box-sizing: border-box; }
        .txt-input { flex: 2; } .tag-select { flex: 1; }
        button { background-color: #e07a5f; color: white; padding: 14px; font-size: 16px; border: none; border-radius: 5px; cursor: pointer; font-weight: bold; width: 100%; margin-top: 15px; }
        .btn-sec { background-color: #2b7a78; margin-bottom: 10px; }
        .auth-banner { background: #fde8e8; border: 1px solid #f8b4b4; color: #9b1c1c; padding: 12px; border-radius: 6px; margin-bottom: 20px; font-weight: bold; }
    </style>
</head>
<body>
    <div class="admin-card">
        <h2 style="text-align: center; color: #e07a5f;">Instructor Catalog Matrix Controller</h2>
        <p style="text-align: center; color: #666; margin-bottom: 25px;">Dynamic array injection direct to production MongoDB cluster document namespaces.</p>

        <form action="/api/quiz/update" method="POST">
            <!-- Security Gate: Passphrase token checking matching M1 boundaries -->
            <div class="auth-banner">
                <label style="color: #9b1c1c; display:inline;">Gateway Authentication Key: </label>
                <input type="password" name="auth_token" style="width:50%; display:inline; padding:5px;" placeholder="Required" required>
            </div>

            <div id="dynamic_container">
                {% for item in current_items %}
                <div class="item-row">
                    <div class="txt-input">
                        <label>Application Content Text:</label>
                        <input type="text" name="content_text[]" value="{{ item.content_text }}" style="width:100%;" required>
                    </div>
                    <div class="tag-select">
                        <label>Target Schema Tag:</label>
                        <select name="correct_tag[]" style="width:100%;">
                            <option value="tag_game" {% if item.correct_tag == 'tag_game' %}selected{% endif %}>Game Domain</option>
                            <option value="tag_chat" {% if item.correct_tag == 'tag_chat' %}selected{% endif %}>Communication</option>
                        </select>
                    </div>
                </div>
                {% endfor %}
            </div>

            <button type="button" class="btn-sec" onclick="appendInputRow()">+ Inject Additional Text Row Dynamic Element</button>
            <button type="submit">Commit Matrix Overwrite Changes to Cloud MongoDB</button>
        </form>
        <p style="text-align:center;"><a href="/" style="color:#2b7a78; font-weight:bold; text-decoration:none;">← Cancel and Return to Student Engine View</a></p>
    </div>

    <script>
        // Frontend Dynamic Expansion: Satisfies zero-hardcoding constraint across infinite item sizes
        function appendInputRow() {
            let container = document.getElementById("dynamic_container");
            let newRow = document.createElement("div");
            newRow.className = "item-row";
            newRow.innerHTML = `
                <div class="txt-input">
                    <label>Application Content Text:</label>
                    <input type="text" name="content_text[]" style="width:100%;" placeholder="e.g. Slack" required>
                </div>
                <div class="tag-select">
                    <label>Target Schema Tag:</label>
                    <select name="correct_tag[]" style="width:100%;">
                        <option value="tag_game">Game Domain</option>
                        <option value="tag_chat">Communication</option>
                    </select>
                </div>
            `;
            container.appendChild(newRow);
        }
    </script>
</body>
</html>
\"\"\"

# ------------------------------------------------------------------------------
# 4. CONTROLLER SCHEMAS & ROUTING ENGINE (Dynamic Synchronization Layer)
# ------------------------------------------------------------------------------
@app.route('/')
def load_student_portal():
    active_quiz = quizzes_col.find_one({"quiz_id": "global_quiz"})
    return render_template_string(STUDENT_TEMPLATE, quiz=active_quiz)

@app.route('/edit-quiz')
def load_instructor_workspace():
    active_quiz = quizzes_col.find_one({"quiz_id": "global_quiz"})
    return render_template_string(INSTRUCTOR_TEMPLATE, current_items=active_quiz['items'])

@app.route('/api/quiz/update', methods=['POST'])
def process_instructor_catalog_overwrite():
    \"\"\"Validates secure passphrase mapping tokens and pushes dynamic item vectors to database.\"\"\"
    token_input = request.form.get("auth_token")

    # M1 Authentication Defense Boundary
    if token_input != ADMIN_PASSWORD:
        return jsonify({"status": "rejected", "reason": "Access Denied: Invalid Security Gateway Authentication Key."}), 401

    texts_array = request.form.getlist("content_text[]")
    tags_array = request.form.getlist("correct_tag[]")

    rebuilt_items = []
    for idx, txt in enumerate(texts_array):
        icon = "🎮" if tags_array[idx] == "tag_game" else "💬"
        rebuilt_items.append({
            "id": f"dynamic_item_{idx}",
            "content_text": txt,
            "correct_tag": tags_array[idx],
            "display_asset": f"{icon} {txt}"
        })

    quizzes_col.update_one(
        {"quiz_id": "global_quiz"},
        {"$set": {
            "quiz_id": "global_quiz",
            "title": "Application Functional Categorization Quiz",
            "items": rebuilt_items
        }},
        upsert=True
    )
    return redirect(url_for('load_student_portal'))

@app.route('/api/submit', methods=['POST'])
def process_student_scoring_matrix():
    telemetry_data = request.json if request.is_json else {}
    active_quiz = quizzes_col.find_one({"quiz_id": "global_quiz"})

    score = 0
    items_list = active_quiz.get('items', [])
    if items_list:
        weight_factor = 100 // len(items_list)
        for item in items_list:
            if telemetry_data.get(item['id']) == item['correct_tag']:
                score += weight_factor

    results_col.insert_one({
        "calculated_score": score,
        "is_mocked_env": db_mocked,
        "telemetry_source": "production_render_live"
    })
    return jsonify({"score": score, "db_logged": True if not db_mocked else False})

if __name__ == '__main__':
    runtime_port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=runtime_port)
"""

# Append to the end of the file in append mode ("a").
with open("app.py", "a", encoding="utf-8") as f:
    f.write(code_part2)

print("✓ Part 2 successfully appended! app.py is now 100% complete and integrated.")